### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by ChalakaNuwan**
Resolving conflicts with other modules

### CODE REVIEW

**Comment by claydanford** [comment]
Hi @ChalakaNuwan, can you give more details on this PR? According to the documentation, this version should work as expected with the pessimist version constraint:

> ~>: pessimistic constraint operator, constraining both the oldest and newest version allowed. For example, ~> 0.9 is equivalent to >= 0.9, < 1.0, and ~> 0.8.4, is equivalent to >= 0.8.4, < 0.9

**Comment by ChalakaNuwan** [comment]
@claydanford 
Had bellow issue when i am using this module with aws-vpn module and after change like this. it worked 
terraform {
  required_version = ">= 0.12"

  required_providers {
    #aws      = "~> 2.25.0"
    aws = "~> 2.53"
    template = "2.1.2"
  }
}


`Initializing modules...
Downloading neiman-marcus/jenkins-ha-agents/aws 2.5.5 for jenkins_ha_agents_2...
- jenkins_ha_agents_2 in .terraform/modules/jenkins_ha_agents_2

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

No provider "aws" plugins meet the constraint "~> 2.25.0,~> 2.53,~> 2.53".

The version constraint is derived from the "version" argument within the
provider "aws" block in configuration. Child modules may also apply
provider version constraints. To view the provider versions requested by each
module in the current configuration, run "terraform providers".

To proceed, the version constraints for this provider must be relaxed by
either adjusting or removing the "version" argument in the provider blocks
throughout the configuration.


Error: no suitable version is available`

**Comment by claydanford** [comment]
@ChalakaNuwan, instead of upgrading, can you drop the ending zero and try? It would be better to maintain with the current version.

**Comment by ChalakaNuwan** [comment]
@claydanford droping the ending zero  is working . i will raise a PR

**Pull request closed without merging**
